from __future__ import annotations

from tools import write_text_file
from langgraph.func import task
from langgraph.func import task
from langgraph.graph import StateGraph, START, END

from runtime import state
from runtime.state import RunState
from schemas.plan_schema import PlanSchema
from schemas.execution_schema import ExecutionSchema
from schemas.verification_schema import VerificationSchema
from schemas.common_types import CompletionStatus, Verdict, WorkflowStage, FinalStatus


def plan_node(state: RunState) -> dict:
    task = state.task

    plan = PlanSchema(
        task_summary=f"Plan for task: {task.title}",
        assumptions=[
            "Task input is valid",
            "Required project context is already available",
        ],
        execution_steps=[
            "Review the task objective and constraints",
            "Prepare the expected artifact structure",
            "Perform the requested work using approved tools",
        ],
        required_tools=task.allowed_tools,
        expected_artifacts=[task.expected_output],
        risks=[
            "Missing context could reduce output quality",
            "Tool restrictions may prevent full completion",
        ],
        escalation_needed=False,
    )

    return {
        "current_stage": WorkflowStage.PLANNING,
        "plan": plan,
    }


def execute_node(state: RunState) -> dict:
    task = state.task


    report_content = f"""# Baseline Engineering Artifact Report

**Task Title**:
{task.title}

**Objective*:* 
{task.objective}

**Context**:
{task.context}

**Constraints**:
{chr(10).join(f"- {c}" for c in task.constraints)}

#Execution Summary
The Artifact was generated by the baseline LangGraph workflow.

**Approved Tools
{chr(10).join(f"- {t}" for t in task.allowed_tools)}
 """   
    
    artifact_path = write_text_file(
        run_id=state.run_id,
        filename=task.expected_output,
        content=report_content
    )

    execution = ExecutionSchema(
        actions_taken=[
            "Reviewed task and plan",
            "Simulated constrained execution",
            f"wrote artifact to {artifact_path}",
        ],
        tools_used=task.allowed_tools,
        artifacts_created=[artifact_path],
        errors=[],
        deviations_from_plan=[],
        completion_status=CompletionStatus.COMPLETED,
    )

    return {
        "current_stage": WorkflowStage.EXECUTION,
        "execution": execution,
    }


def verify_node(state: RunState) -> dict:
    execution = state.execution

    if execution is None:
        verification = VerificationSchema(
            verdict=Verdict.FAIL,
            issues_found=["Execution output is missing"],
            policy_violations=[],
            quality_assessment="Verification could not complete because execution data was absent.",
            recommended_next_step="Retry execution",
        )
        return {
            "current_stage": WorkflowStage.VERIFICATION,
            "verification": verification,
        }

    if execution.completion_status == CompletionStatus.COMPLETED:
        verification = VerificationSchema(
            verdict=Verdict.PASS,
            issues_found=[],
            policy_violations=[],
            quality_assessment="Execution output is complete and reviewable for the baseline workflow.",
            recommended_next_step="Proceed to finalization",
        )
    else:
        verification = VerificationSchema(
            verdict=Verdict.RETRY,
            issues_found=["Execution did not complete successfully"],
            policy_violations=[],
            quality_assessment="Execution output is incomplete for the baseline workflow.",
            recommended_next_step="Retry execution or escalate",
        )

    return {
        "current_stage": WorkflowStage.VERIFICATION,
        "verification": verification,
    }


def finalize_node(state: RunState) -> dict:
    verification = state.verification

    if verification is None:
        return {
            "current_stage": WorkflowStage.FAILED,
            "final_status": FinalStatus.FAILED,
            "final_summary": "Run ended without verification output.",
        }

    verdict_to_status = {
        Verdict.PASS: FinalStatus.SUCCESS,
        Verdict.FAIL: FinalStatus.FAILED,
        Verdict.RETRY: FinalStatus.PARTIAL,
        Verdict.ESCALATE: FinalStatus.ESCALATED,
    }

    final_status = verdict_to_status.get(verification.verdict, FinalStatus.FAILED)

    return {
        "current_stage": WorkflowStage.COMPLETE,
        "final_status": final_status,
        "final_summary": (
            f"Run completed with verification verdict "
            f"'{verification.verdict.value}' and final status "
            f"'{final_status.value}'."
        ),
    }


def route_after_verification(state: RunState) -> str:
    verification = state.verification
    if verification and verification.verdict == Verdict.RETRY:
        return "execute"
    return "finalize"


def build_graph():
    graph = StateGraph(RunState)

    graph.add_node("plan", plan_node)
    graph.add_node("execute", execute_node)
    graph.add_node("verify", verify_node)
    graph.add_node("finalize", finalize_node)

    graph.add_edge(START, "plan")
    graph.add_edge("plan", "execute")
    graph.add_edge("execute", "verify")
    graph.add_conditional_edges(
        "verify",
        route_after_verification,
        {
            "execute": "execute",
            "finalize": "finalize",
        },
    )
    graph.add_edge("finalize", END)

    return graph.compile()
